### ISSUE TITLE
CLI Cheatsheet

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra-documentation#111]
Short and efficient page providing commands, descriptions and examples of common tasks!
@jmorel, @samlesu, @Esadruhn I don't remember if something specific was agreed about this, but I'd be happy to start and to get your feedbacks!

**Comment by jmorel** [comment]
I believe that @jeandut was the one who suggested this.
His idea was that this could include:
* basic commands (ex: login + register an algo and a tuple)
* gotchas (what the key depends on for example)
