### ISSUE TITLE
[BUG] Dead link in Titanic Example

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/substra-documentation#131]
The link pointing to the titanic example on github is broken: https://doc.substra.ai/setup/demo.html#follow-titanic-example
It's the link on the **repository** word in the sentence:  `see this repository for further details.`

**Comment by natct10** [comment]
Woups, thank you @RomainGoussault for spotting this! There is indeed a `.md` that is missing at the end of the url, I will fix this!
