### ISSUE TITLE
Add permissions note for assets

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra-documentation#145]
with screenshots?

**Comment by RomainGoussault** [comment]
It will be very useful to have a dedicated page on permissions !

**Comment by natct10** [comment]
> It will be very useful to have a dedicated page on permissions !

Nice, thank you for your insight, will do!

**Comment by natct10** [comment]
> It will be very useful to have a dedicated page on permissions !
> 
>     * Default permissions
> 
>     * How to change permissions

Not sure about the permission modification, but I'll look into it!
