### ISSUE TITLE
Describe errors and exceptions

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra-documentation#148]
In the usage/client section, from a user perspective, it would be useful to provide a description (and tips) about errors and exceptions raised while manipulating assets.

See: https://github.com/SubstraFoundation/substra-backend/blob/master/backend/substrapp/tasks/exceptions.json

@camillemarini Would you like to add any comment/example on this issue? I will open a draft PR as soon as possible on this!

**Comment by camillemarini** [comment]
No comment it corresponds to what we discussed, thank you @natct10  :-)
