### ISSUE TITLE
Debugging - Troubleshooting for Docker container crash

### ISSUE THREAD

**Issue by Fabien-GELUS** [SubstraFoundation/substra-documentation#152]
## Introduction

In debug mode, when running `add_train_tuple` with (too) large data, a Docker container is launched and then exit with last log `substratools.algo - launching training task` (no stacktrace).
If we monitor the container with [docker stats](https://docs.docker.com/engine/reference/commandline/stats/ ), we can clearly see that its memory exploded.
A fix for this is to set a higher shm_size in [spawner.py](https://github.com/SubstraFoundation/substra/blob/master/substra/sdk/backends/local/compute/spawner.py#L67)

## Describe the ideal feature

We could add this advice in a troubleshooting section in the [local debug mode doc](https://doc.substra.ai/debugging.html)

**Comment by natct10** [comment]
Oh nice, would you kindly share here the message you get with `docker stats`, please?

**Comment by Fabien-GELUS** [comment]
I think there is no message, we just see the container memory going up to 8go and the container is stopped 😄

**Comment by natct10** [comment]
Okay, thx, noted! 
I might add this to this ongoing [PR](https://github.com/SubstraFoundation/substra-documentation/pull/150), even if there is no error message. Please let me know if you see some other recurrent errors to add there!

**Comment by natct10** [comment]
Done in #150
