### ISSUE TITLE
Remove link to the forum

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/substra-documentation#51]
There is a link to the Discourse forum in CONTRIBUTING.html#i-don-t-want-to-read-this-whole-thing-i-just-have-a-question

**Comment by natct10** [comment]
Hi @bowni thank you for raising this point! The PR is already opened: <https://github.com/SubstraFoundation/.github/pull/7>. Once merge, it will be fetched in the documentation during the next build!

**Comment by natct10** [comment]
Done @bowni : https://doc.substra.ai/contribute/CONTRIBUTING.html#i-don-t-want-to-read-this-whole-thing-i-just-have-a-question
