### ISSUE TITLE
Setup : CLI "substra config" command is wrong

### ISSUE THREAD

**Issue by Fabien-GELUS** [SubstraFoundation/substra-documentation#59]
I'm on a Ubuntu VM. 
I installed the Substra CLI v0.5 with 
`sudo pip3 install substra`

I got an error when running this command : 
`sudo substra config http://substra-backend.node-1.com`
The error : 
```
Usage: substra config [OPTIONS] URL
Try 'substra config --help' for help.

Error: Missing option '--username' / '-u'.
```
However this command worked for me : 
`sudo substra config -u "node-1" -p 'p@$swr0d44' http://substra-backend.node-1.com
`
and then 
`sudo substra login
`
Could you change it in the doc ?
Thanks

**Comment by natct10** [comment]
Thank you @Fabien-GELUS !

**Comment by jmorel** [comment]
@natct10 this is related to the premature merge of #53

**Comment by natct10** [comment]
> @natct10 this is related to the premature merge of #53

Okay thx @jmorel
