### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/substra-documentation#93]
- [x] Add badges to the substra-documentation readme
- [x] Add License badge
- [x] Update slack url to point towards an invitation link

**Comment by bowni** [comment]
Also, I would add:

- [ ] Update Slack badge link to an invitation link

**Comment by natct10** [comment]
> Also, I would add:
> 
>     * [ ]  Update Slack badge link to an invitation link

Oh yes, thank you @bowni ! Do you have any idea how/where I could find/generate such a link?

**Comment by natct10** [comment]
> > Also, I would add:
> > ```
> > * [ ]  Update Slack badge link to an invitation link
> > ```
> 
> Oh yes, thank you @bowni ! Do you have any idea how/where I could find/generate such a link?

I'll user the one you used in contributivity: https://substra.us18.list-manage.com/track/click?e=2effed55c9&id=fa49875322&u=385fa3f9736ea94a1fcca969f
